/* 
 * htsget
 *
 * This data retrieval API bridges from existing genomics bulk data transfers to a client/server model
 *
 * OpenAPI spec version: 1.1.1
 * Contact: security-notification@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct HtsgetResponse {
  #[serde(rename = "htsget")]
  htsget: Option<::models::HtsgetResponseHtsget>
}

impl HtsgetResponse {
  pub fn new() -> HtsgetResponse {
    HtsgetResponse {
      htsget: None
    }
  }

  pub fn set_htsget(&mut self, htsget: ::models::HtsgetResponseHtsget) {
    self.htsget = Some(htsget);
  }

  pub fn with_htsget(mut self, htsget: ::models::HtsgetResponseHtsget) -> HtsgetResponse {
    self.htsget = Some(htsget);
    self
  }

  pub fn htsget(&self) -> Option<&::models::HtsgetResponseHtsget> {
    self.htsget.as_ref()
  }

  pub fn reset_htsget(&mut self) {
    self.htsget = None;
  }

}



