/* 
 * htsget
 *
 * This data retrieval API bridges from existing genomics bulk data transfers to a client/server model
 *
 * OpenAPI spec version: 1.1.1
 * Contact: security-notification@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

/// InvalidInput : The request parameters do not adhere to the specification

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InvalidInput {
}

impl InvalidInput {
  /// The request parameters do not adhere to the specification
  pub fn new() -> InvalidInput {
    InvalidInput {
    }
  }

}



