/* 
 * htsget
 *
 * This data retrieval API bridges from existing genomics bulk data transfers to a client/server model
 *
 * OpenAPI spec version: 1.1.1
 * Contact: security-notification@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

/// InvalidRange : The requested range cannot be satisfied

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InvalidRange {
}

impl InvalidRange {
  /// The requested range cannot be satisfied
  pub fn new() -> InvalidRange {
    InvalidRange {
    }
  }

}



