/* 
 * htsget
 *
 * This data retrieval API bridges from existing genomics bulk data transfers to a client/server model
 *
 * OpenAPI spec version: 1.1.1
 * Contact: security-notification@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

/// UnsupportedFormat : The requested file format is not supported by the server

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UnsupportedFormat {
}

impl UnsupportedFormat {
  /// The requested file format is not supported by the server
  pub fn new() -> UnsupportedFormat {
    UnsupportedFormat {
    }
  }

}



