/* 
 * htsget
 *
 * This data retrieval API bridges from existing genomics bulk data transfers to a client/server model
 *
 * OpenAPI spec version: 1.1.1
 * Contact: security-notification@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UrlsItems {
  #[serde(rename = "url")]
  url: String,
  #[serde(rename = "headers")]
  headers: Option<Value>
}

impl UrlsItems {
  pub fn new(url: String) -> UrlsItems {
    UrlsItems {
      url: url,
      headers: None
    }
  }

  pub fn set_url(&mut self, url: String) {
    self.url = url;
  }

  pub fn with_url(mut self, url: String) -> UrlsItems {
    self.url = url;
    self
  }

  pub fn url(&self) -> &String {
    &self.url
  }


  pub fn set_headers(&mut self, headers: Value) {
    self.headers = Some(headers);
  }

  pub fn with_headers(mut self, headers: Value) -> UrlsItems {
    self.headers = Some(headers);
    self
  }

  pub fn headers(&self) -> Option<&Value> {
    self.headers.as_ref()
  }

  pub fn reset_headers(&mut self) {
    self.headers = None;
  }

}



